# Generated by Django 5.1.1 on 2024-12-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_phone_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
